version: '3.7'

services:
  gateway:
    container_name: go-grpc-haproxy_gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - RESOURCE_ADDRESS=haproxy:443
    depends_on:
      - resource
      - haproxy

  haproxy:
    container_name: go-grpc-haproxy_haproxy
    image: haproxy:2.1.3
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "80:80"
    depends_on:
      - resource

  resource:
    container_name: go-grpc-haproxy_resource
    build:
      context: ./resource
      dockerfile: Dockerfile
