version: '3.7'

services:
  haproxy:
    container_name: go-grpc-haproxy_haproxy
    image: haproxy:2.1.3
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      - "./haproxy/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem"
      - "./haproxy/server.crt:/usr/local/etc/haproxy/server.crt"
    ports:
      - "80:80"
    depends_on:
      - resource

  resource:
    container_name: go-grpc-haproxy_resource
    build:
      context: ./resource
      dockerfile: Dockerfile
