version: '3.7'

services:
  gateway:
    container_name: sm_be_gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - RESOURCE_ADDRESS=haproxy:443
    depends_on:
      - resource
      - haproxy

  resource:
    container_name: sm_be_resource
    build:
      context: resource
      dockerfile: Dockerfile
    ports:
      - 3002:3002
