version: '3.7'

services:
  haproxy:
    image: haproxy:2.1.3-alpine
    container_name: sm-lb-haproxy
    volumes:
      - ../haproxy/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
    depends_on:
      - resource
