version: '3.7'

services:
  mariadb-master:
    image: mariadb:${MARIADB_VERSION}
    container_name: sm_db_master
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=root
      - MYSQL_DATABASE=service_mesh
      - MYSQL_ROOT_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=yes

  mariadb-slave:
    image: mariadb:${MARIADB_VERSION}
    container_name: sm_db_slave
    depends_on:
      - mariadb-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=root
      - MYSQL_DATABASE=service_mesh
      - MYSQL_MASTER_HOST=mariadb-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=yes
